from enum import IntEnum, StrEnum


ADVERTISING_ID = "4f1d752c-e7ab-4d5c-b028-4a3b5a416246"
MD5_SECRET = "rwmkxhgi6;578i650"
PACKAGE_NAME = "hdad_google"

GAME_CD = "1001"
APP_CHANNEL = "GOOGLEPLAY"
TEST_ENTRY_ENABLE = False
NET_PROCESS_TIPS = False
TEST_RES_RECORD = False
BUILD_ENTRIES_ENABLE = True
TUTORIAL_ENABLE = True
NET_TIMEOUT = 90
PAY_NET_TIMEOUT = 180
ATTENUATION_COEFFCIENT = 3
MINI_GAME_TEST = False
SPINE_TEST_ENABLE = False
URL_GOOGLE_PLAY_ANDROID = "market://details?id=com.droidhang.ad"
URL_GOOGLE_PLAY_WEB = "https://play.google.com/store/apps/details?id=com.droidhang.ad"
URL_APP_STORE_IOS = "https://apps.apple.com/us/app/idle-heroes/id1153461915"
URL_ONESTORE = "http://onesto.re/0000721940"
URL_FACEBOOK_ANDROID = "fb://page/1717588861824432"
URL_FACEBOOK_IOS = "fb://profile/1717588861824432"
URL_FACEBOOK_WEB = "https://www.facebook.com/IdleHeroes"
URL_TWITTER_WEB = "https://twitter.com/IdleHeroes"
URL_TWITTER_WEB_JP = "https://twitter.com/IdleHeroesJP"
URL_WEIBO_WEB = "http://weibo.com/idleheroes"
TAG_WAIT_NET = 1000001
TAG_RECONNECT_DIALOG = 1000002
TAG_RED_DOT = 1000003
TAG_LEVEL_UP = 1000004
TAG_UNLOCKF_UNC = 1000005
TAG_RESUME_BTN = 1000006
POPUP_DARK_OPACITY = 204
Z_ORDER_TOP = 1000
Z_ORDER_BOTTOM = -1000
Z_ORDER_BELOW_BOTTOM = -1001
Z_ORDER_SWALLOW_TOP = 99999
GROUP_0 = 0
GROUP_1 = 1
GROUP_2 = 2
GROUP_3 = 3
GROUP_4 = 4
GROUP_5 = 5
GROUP_6 = 6
GROUP_7 = 7
QUALITY_1 = 1
QUALITY_2 = 2
QUALITY_3 = 3
QUALITY_4 = 4
QUALITY_5 = 5
QUALITY_6 = 6
QUALITY_7 = 7
UNIT_KIND_DAMAGE = 1
UNIT_KIND_DEFENSE = 2
UNIT_KIND_SUPPORT = 3
UNIT_KIND_CONTROL = 4
UNIT_KIND_EXP_FOOD = 5
ITEM_ID_COIN = 1
ITEM_ID_GEM = 2
ITEM_ID_PLAYER_EXP = 3
ITEM_ID_GUILD_COIN = 4
ITEM_ID_GUILD_EXP = 5
ITEM_ID_LUCKY_COIN = 6
ITEM_ID_RUNE_COIN = 7
ITEM_ID_VIP_EXP = 9
ITEM_ID_HERO_EXP = 10
ITEM_ID_EVOLVE_EXP = 11
ITEM_ID_LOVE = 12
ITEM_ID_ENERGY = 13
ITEM_ID_TRIAL_TL = 14
ITEM_ID_DREAM_TL = 625
ITEM_ID_CRYSTAL_PIECE = 15
ITEM_ID_BRAVE = 16
ITEM_ID_ARENA_SHOP = 17
ITEM_ID_BREAD = 19
ITEM_ID_SP_REPLACE = 20
ITEM_ID_SP_SUMMON = 21
ITEM_ID_SP_FIGHT = 22
ITEM_ID_TAVERN_LOW = 28
ITEM_ID_TAVERN_HIGH = 29
ITEM_ID_SP_FIGHT2 = 30
ITEM_ID_SP_WINNER_HEAD = 25
ITEM_ID_SP_LOVER_HEAD = 32
ITEM_ID_SP_F3V3_HEAD_1 = 33
ITEM_ID_SP_F3V3_HEAD_2 = 34
ITEM_ID_SP_F3V3_HEAD_3 = 35
ITEM_ID_SP_F3V3_HEAD_4 = 36
ITEM_ID_SP_F3V3_HEAD_5 = 37
ITEM_ID_SP_WARM = 38
ITEM_ID_SP_FIGHT3 = 39
ITEM_ID_PET_DEVIL = 40
ITEM_ID_PET_CHAOS = 41
ITEM_ID_SP_WARM2 = 42
ITEM_ID_SP_FIGHT4 = 47
ITEM_ID_SP_WARM3 = 48
ITEM_ID_SP_WARM4 = 49
ITEM_ID_SP_FIRSTYEAR = 52
ITEM_ID_SP_FIGHT5 = 57
ITEM_ID_SP_WARM5 = 59
ITEM_ID_SP_FIGHT6 = 60
ITEM_ID_SP_LOVE = 61
ITEM_ID_SP_FIGHT7 = 62
ITEM_ID_SP_RABBIT = 63
ITEM_ID_SP_BEAR = 64
ITEM_ID_SP_FIGHT8 = 65
ITEM_ID_SP_SUB = 66
ITEM_ID_SP_HW = 67
ITEM_ID_PUMPKIN = 68
ITEM_ID_BELL = 69
ITEM_ID_BUILD_STONE = 72
ITEM_ID_SP_FIGHT9 = 70
ITEM_ID_SP_VPLI1 = 71
ITEM_ID_SOUL_BOX = 73
ITEM_ID_SP_MASK = 88
ITEM_ID_SP_FIGHT10 = 89
ITEM_ID_SP_CHRISTMAS = 93
ITEM_ID_SP_FIGHT11 = 102
ITEM_ID_MAGICGLIM = 110
ITEM_ID_CHOCO = 111
ITEM_ID_SP_NEWYEAR1 = 112
ITEM_ID_SP_FIGHT12 = 113
ITEM_ID_STONETABLET = 124
ITEM_ID_STONEFIGURE = 125
ITEM_ID_SP_FIGHT13 = 126
ITEM_ID_DARKREMAINS = 131
ITEM_ID_SP_FIGHT14 = 138
ITEM_ID_SP_FIGHT15 = 140
ITEM_ID_ANNIVERSARY = 142
ITEM_ID_SP_DEMON = 143
ITEM_ID_SP_FIGHT16 = 152
ITEM_ID_SP_FIGHT17 = 157
ITEM_ID_SP_FIGHT18 = 167
ITEM_ID_COLOR_CRYSTAL = 168
ITEM_ID_LIGHT_DARK_CRYSTAL = 169
ITEM_ID_GLORY = 170
ITEM_ID_ICECREAM = 173
ITEM_ID_SP_MOONCAKE = 175
ITEM_ID_SP_AFRICA1 = 178
ITEM_ID_SP_AFRICA2 = 179
ITEM_ID_SP_AFRICA3 = 180
ITEM_ID_FLOWERCAKE = 181
ITEM_ID_SP_HALLOMAS = 187
ITEM_ID_MAPLELEAF = 188
ITEM_ID_CHICKEN = 190
ITEM_ID_SP_THANK = 191
ITEM_ID_ABS_CRYSTAL = 194
ITEM_ID_CHRISTMAS_CARD = 196
ITEM_ID_SNOWFLAKE = 195
ITEM_ID_SP_CHRISTMAS2 = 197
ITEM_ID_SP_NEW_YEAR = 205
ITEM_ID_CANDY_FLOSS = 206
ITEM_ID_SP_CHINESE_NEW_YEAR = 215
ITEM_ID_RUDDER = 217
ITEM_ID_LUCKY_GRASS = 219
ITEM_ID_SP_FLOWER_CIRCLE = 220
ITEM_ID_MUSIC_BOX = 242
ITEM_ID_SP_ANNIVERSARY = 240
ITEM_ID_SP_CRYSTAL = 244
ITEM_ID_SP_MID_AUTUMN = 253
ITEM_ID_SP_WONDER_BOOK = 259
ITEM_ID_SNOWFLAKE = 276
ITEM_ID_SNOWMAN = 277
ITEM_ID_ROSE = 295
ITEM_ID_CHOCOLATE = 296
ITEM_ID_MEDAL = 312
ITEM_ID_BAGSPACE = 313
ITEM_ID_CLOWN_MASK = 317
ITEM_ID_ORMUS_ARTIFACT = 303
ITEM_ID_VOUCHER = 338
ITEM_ID_VOUCHER2 = 1370
ITEM_ID_INVITATION = 363
ITEM_ID_ANNIVERSARY_TICKET = 354
ITEM_ID_INVITATION = 363
ITEM_ID_BLACK_SCORE = 449
ITEM_ID_NEW_YEAR = 470
ITEM_ID_MATCH_SCORE = 481
ITEM_ID_PUB_ITEM_1 = 573
ITEM_ID_PUB_ITEM_2 = 574
ITEM_ID_PUB_ITEM_3 = 575
ITEM_ID_PUB_ITEM_4 = 576
ITEM_ID_HALLOWEEN_ITEM = 736
ITEM_ID_THANKSGIVING_ITEM = 764
ITEM_ID_LOVE_ITEM = 869
ITEM_ID_SPRINGFESTIVAL_ITEM_1 = 853
ITEM_ID_FOREST_ITEM_1 = 893
ITEM_ID_ARTIFACT_BOX = 938
ITEM_ID_HALLOWEEN_ITEM_1 = 1215
ITEM_ID_HALLOWEEN_ITEM_2 = 1216
ITEM_ID_HALLOWEEN_ITEM_3 = 1217
ITEM_ID_HALLOWEEN_ITEM_4 = 1218
ITEM_ID_NEWYEAR_MOMP_ITEM = 1302
ITEM_ID_STAR_STONE = 854
ITEM_ID_STAR_GEM = 855
ITEM_ID_CRUSH_STAR_GEM = 856
ITEM_ID_NEW_STAR_GEM = 1261
ITEM_ID_FREE_STAR = 885
ITEM_ID_SPACE_TIME_TREE_WOOD = 2008
ITEM_ID_SPACE_TIME_TREE_STAR = 2009
ITEM_ID_SPACE_TIME_TREE_ADVANCE_1 = 2010
ITEM_ID_SPACE_TIME_TREE_ADVANCE_2 = 2011
ITEM_ID_SPACE_TIME_TREE_ADVANCE_3 = 2012
ITEM_ID_SPACE_TIME_TREE_ADVANCE_4 = 2013
ITEM_ID_SPACE_TIME_TREE_ADVANCE_4 = 2014
ITEM_ID_SPACE_TIME_TREE_ADVANCE_5 = 2015
ITEM_ID_ICEBABY = 26
ITEM_ID_HTASK_LOW = 28
ITEM_ID_HTASK_HIGH = 29
ITEM_ID_SPRINGBABY = 43
ITEM_ID_FISHBABY = 51
ITEM_ID_TINYSNOWMAN = 92
ITEM_ID_GUILDFIRE = 117
ITEM_ID_ELEMENT = 165
ITEM_ID_CHIP = 12002
ITEM_ID_ADVANCED_CHIP = 58
ITEM_ID_ENCHANT = 10001
ITEM_ID_SMITH_CRYSTAL = 10002
ITEM_ID_FORGE = 10008
ITEM_ID_GACHA = 12000
ITEM_ID_ARENA = 12001
ITEM_ID_SUPERGACHA = 12003
ITEM_ID_BROKEN = 50
ITEM_ID_PIECE_Q4 = 40001
ITEM_ID_PIECE_Q5 = 40002
ITEM_ID_PIECE_Q3 = 40003
ITEM_ID_EXQ_LIGHT_Q5 = 40046
ITEM_ID_EXQ_DARK_Q5 = 40045
ITEM_ID_EXQ_Q5 = 40039
ITEM_ID_PIECE_GROUP_Q5 = 40010
ITEM_ID_PIECE_GROUP_Q4 = 40020
ITEM_ID_PIECE_GROUP_Q3 = 40030
ITEM_ID_PIECE_SKIN = 60001
ITEM_ID_SPACE_TIME_HEART = 2001
ITEM_ID_SPACE_TIME_GACHA = 2101
ITEM_ID_PET_COOKY = 1277
ITEM_ID_SPACE_TIME_CRYSTAL = 2099
ITEM_ID_SPACE_TIME_STARS_CHIP = 2002
ITEM_ID_SPACE_TIME_STARS = 2003
ITEM_ID_SPACE_TIME_TREE = 975
ITEM_ID_SPACE_TIME_TREE_CHIP_A = 976
ITEM_ID_SPACE_TIME_TREE_CHIP_B = 977
ITEM_ID_SPACE_TIME_TREE_CHIP_C = 978
ITEM_ID_SPACE_TIME_TREE_CHIP_D = 979
ITEM_ID_SKIN_TICKET = 515
ITEM_ID_GUILD_GOLD = 516
ITEM_ID_SOUL_RIDER = 534
ITEM_ID_HOME_WOOD = 626
ITEM_ID_HOME_STONE = 627
ITEM_ID_HOME_IRON = 628
ITEM_ID_HOME_SILVER = 629
ITEM_ID_HOME_ELIXIR = 630
ITEM_ID_HOME_WOOD2 = 631
ITEM_ID_HOME_STONE2 = 632
ITEM_ID_HOME_ELIXIR2 = 643
ITEM_ID_HOME_ST_STONE = 72
ITEM_ID_SANCTUARY_BASE_COIN = 3512
ITEM_ID_GOLD_BAG = 568
ITEM_ID_SILVER_BAG = 569
ITEM_ID_FISH_BONE = 570
ITEM_ID_WISH_COIN = 572
ITEM_ID_CANDY_SCORE = 907
ITEM_ID_QLT_PVP_COIN = 1052
ITEM_ID_SILK = 1159
ITEM_ID_SUPER_BREAK_STONE = 1209
ITEM_ID_SPRING_FESTIVAL_RED_ENVELOPE = 1325
ITEM_ID_NEW_YEAR_DEVIL_ITEM = 1759
ITEM_ID_NEW_YEAR_DEVIL_ITEM_MEAT = 1760
ITEM_ID_COLLECTION_TICKET = 1321
ITEM_ID_COLLECTION_HEART = 1322
ITEM_ID_1562 = 1562
ITEM_ID_1563 = 1563
ITEM_ID_1564 = 1564
ITEM_ID_HALLOWEEN_CHARM = 1658
ITEM_ID_SPRING_ITEM = 1795


class EXCHANGE_TYPE(IntEnum):
    Type_1563_1564 = 1
    PowerCrystal = 2


ITEM_KIND_MONEY = 1
ITEM_KIND_EQUIP = 2
ITEM_KIND_ITEM = 3
ITEM_KIND_GIFT = 4
ITEM_KIND_HERO_PIECE = 5
ITEM_KIND_SCROLL_PIECE = 6
ITEM_KIND_TREASURE_PIECE = 7
ITEM_KIND_SKIN_PIECE = 9
ITEM_KIND_HOME_SKIN_PIECE = 10
ITEM_KIND_KERNEL_PIECE = 11
ITEM_KIND_COLLECT_PIECE = 12
ITEM_KIND_POWER_CRYSTAL_PIECE = 13
ITEM_KIND_POWER_CRYSTAL = 14
ICON_ID_HERO_Q6 = 10041
ICON_ID_HERO_Q5 = 10011
ICON_ID_HERO_Q4 = 10021
ICON_ID_HERO_Q3 = 10031
ICON_ID_HERO_EXQ_Q5 = 10042
ICON_ID_HERO_EXQ_LIGHT_AND_DARK_Q5 = 10043
HERO_ID_ANY_Q3 = 3333
HERO_ID_ANY_Q4 = 4444
HERO_ID_ANY_Q5 = 5555
HERO_ID_ANY_Q6 = 6666
HERO_ID_GROUP_Q3 = 3099
HERO_ID_GROUP_Q4 = 4099
HERO_ID_GROUP_Q5 = 5099
HERO_ID_GROUP_Q6 = 6099
HERO_ID_EXQ_LIGHT_Q5 = 7099
HERO_ID_EXQ_DARK_Q5 = 8099
HERO_ID_EXQ_Q5 = 9099
HERO_ID_SKIN = 6001
BUFF_ATK = "atk"
BUFF_HP = "hp"
BUFF_ARM = "arm"
BUFF_SPD = "spd"
BUFF_ENERGY = "energy"
BUFF_HIT = "hit"
BUFF_MISS = "miss"
BUFF_CRIT = "crit"
BUFF_TRUE_ATK = "trueAtk"
BUFF_BRK = "brk"
BUFF_STUN = "stun"
BUFF_ICE = "ice"
BUFF_STONE = "stone"
BUFF_FORBID = "forbid"
BUFF_REVIVE = "revive"
BUFF_CRIT_TIME = "critTime"
BUFF_FREE = "free"
BUFF_SKL_P = "sklP"
BUFF_DEC_DMG = "decDmg"
BUFF_HURT = "hurt"
BUFF_DOT = "dot"
BUFF_HEAL = "heal"
BUFF_HOT = "hot"
BUFF_HEAL_P = "healP"
BUFF_TRUE_HURT = "trueHurt"
BUFF_SIPHON_ATK = "siphonAtk"
BUFF_SIPHON_HP = "siphonHp"
BUFF_SIPHON_ARM = "siphonArm"
BUFF_SHIELD = "shield"
BUFF_BRIER = "brier"
BUFF_DOT_FIRE = "dotFire"
BUFF_DOT_POISON = "dotPoison"
BUFF_DOT_BLOOD = "dotBlood"
BUFF_DOT_SHADOWF = "shadowF"
BUFF_DOT_THU = "dotThu"
BUFF_DOT_BLAST = "dotBlast"
BUFF_DOT_BLASTB = "dotBlastB"
BUFF_DOT_BLASTC = "dotBlastC"
BUFF_ATK_P = "atkP"
BUFF_HP_P = "hpP"
BUFF_ARM_P = "armP"
BUFF_CHANGE_COMBAT = "changeCombat"
BUFF_ADD_HURT = "addHurt"
BUFF_RIMPRESS = "rImpress"
BUFF_CIMPRESS = "cImpress"
BUFF_FIMPRESS = "fImpress"
BUFF_OIMPRESS = "oImpress"
BUFF_KIMPRESS = "kImpress"
BUFF_SIMPRESS = "sImpress"
BUFF_WEAK = "weak"
BUFF_FEAR = "fear"
BUFF_HPBELOW_FEAR = "hpBelowFear"
BUFF_BALANCE = "balance"
BUFF_ATK_TRUEHURT = "atkTrueHurt"
BUFF_CUREPRESS = "curepress"
BUFF_SEEDPRESS = "seedpress"
BUFF_WIND = "wind"
BUFF_BURST_ARM = "burstArm"
BUFF_REF_ARM = "refArm"
BUFF_DARK_SHIELD = "darkShield"
BUFF_CURE_CURSE = "cureCurse"
BUFF_KILLING = "killing"
BUFF_LAVA = "lava"
BUFF_SOULLINKB = "soulLinkB"
BUFF_TAUNT = "taunt"
BUFF_LIGHTF = "lightf"
BUFF_SEAL = "seal"
BUFF_RELIVE = "relive"
BUFF_TMISS = "tmiss"
BUFF_DEVOUR = "devour"
BUFF_SHRINK = "shrink"
BUFF_FAIRYG = "fairyG"
BUFF_EVIL = "evil"
BUFF_TRUEDOT = "trueDot"
BUFF_VANISH = "vanish"
BUFF_PREPARE = "prepare"
BUFF_BLACKHOLE = "blackHole"
BUFF_BLACKHOLEB = "blackHoleB"
BUFF_LURK = "lurk"
BUFF_ARROWL = "arrowL"
BUFF_CHARGE = "charge"
BUFF_DIZZY = "dizzy"
BUFF_BREAKDEF = "breakDef"
BUFF_BLOODDRY = "blooddry"
BUFF_COUNTERHIT = "counterhit"
BUFF_JIANYI = "jianyi"
BUFF_REVENGE = "revenge"
BUFF_REVENGEB = "revengeB"
BUFF_ABYERODE = "abyErode"
BUFF_GUARD = "guard"
BUFF_DECAY = "decay"
BUFF_WITHER = "wither"
BUFF_LIGHTMARK = "lightMark"
BUFF_SOULHURT = "soulHurt"
BUFF_HATRED = "hatred"
BUFF_AID = "aid"
BUFF_SOULDOT = "soulDot"
BUFF_GHOST = "ghost"
BUFF_TRIALMARK = "trialMark"
BUFF_BUBBLE = "bubble"
BUFF_ETEICE = "eteIce"
BUFF_ANNSTONE = "annStone"
BUFF_FOCUS = "focus"
BUFF_ATK_INDIE = "atkIndie"
BUFF_HP_INDIE = "hpIndie"
BUFF_ADDLIGHT = "addLight"
BUFF_DESIRE = "desire"
BUFF_FROST = "frost"
BUFF_EQUIPSHOW1 = "equipShow1"
BUFF_GSWORD = "gSword"
BUFF_SILENT = "silent"
BUFF_CHANGESKL = "changeSkl"
BUFF_CHANGEATT = "changeAtt"
BUFF_HORROR = "horror"
BUFF_WINDIRON = "windIron"
BUFF_SOULSTUN = "soulStun"


class QLT_FACTOR(IntEnum):
    BUFF_ATK = 10000
    BUFF_HP = 10000
    BUFF_SPD = 100


class QLT_FACTOR_UI(IntEnum):
    BUFF_ATK = 1
    BUFF_HP = 1
    BUFF_SPD = 100


ACHIEVE_TYPE_PLAYER_LV = 1
ACHIEVE_TYPE_VIP_LV = 2
ACHIEVE_TYPE_GET_HERO_STAR4 = 3
ACHIEVE_TYPE_GET_HERO_STAR5 = 4
ACHIEVE_TYPE_GET_HERO_STAR6 = 5
ACHIEVE_TYPE_DECOMPOSE_HERO = 6
ACHIEVE_TYPE_GET_EQUIP_GREEN = 7
ACHIEVE_TYPE_GET_EQUIP_RED = 8
ACHIEVE_TYPE_GET_EQUIP_ORANGE = 9
ACHIEVE_TYPE_DECOMPOSE_EQUIP = 10
ACHIEVE_TYPE_ARENA_ATTACK = 11
ACHIEVE_TYPE_ARENA_SCORE = 12
ACHIEVE_TYPE_PASS_FORT = 13
ACHIEVE_TYPE_COMPLETE_HEROTASK4 = 14
ACHIEVE_TYPE_COMPLETE_HEROTASK5 = 15
ACHIEVE_TYPE_COMPLETE_HEROTASK6 = 16
ACHIEVE_TYPE_FRDBOSS = 17
ACHIEVE_TYPE_BRAVE = 18
ACHIEVE_TYPE_CASINO = 19
ACHIEVE_TYPE_SPESUMMON = 20
ACHIEVE_TYPE_WAKE9 = 21
ACHIEVE_TYPE_WAKE10 = 22
ACHIEVE_TYPE_REGISTER = 23
ACHIEVE_TYPE_HIGHSUMMON = 24
ACHIEVE_TYPE_LOVESUMMONFIVE = 25
ACHIEVE_TYPE_COMMONSUMMONFIVE = 26
ACHIEVE_TYPE_SOLOPASS = 27
ACHIEVE_TYPE_WAKE13 = 28
ACHIEVE_TYPE_AFRICA = 29
ACHIEVE_TYPE_FOLLOW1 = 30
ACHIEVE_TYPE_FOLLOW2 = 31
ACHIEVE_TYPE_ARENA_WORLD_LEVEL = 32
ACHIEVE_TYPE_SPACE_TIME_SUMMON = 33
ACHIEVE_TYPE_SPACE_TIME_DIFFICULTY = 34
ACHIEVE_TYPE_SPACE_TIME_EDDY = 35
ACHIEVE_TYPE_SPACE_TIME_SHIP = 36
ACHIEVE_TYPE_DREAM_TOWER = 37
ACHIEVE_TYPE_SEAL_LAND = 38
ACHIEVE_TYPE_DUNGEON = 39
ACHIEVE_TYPE_QLT_STAR = 40
ACHIEVE_TYPE_VOID_HOOK = 41
ACHIEVE_TYPE_OPEN_VOID_HOOK = 42
ACHIEVE_TYPE_COLLECT_SUMMON = 43
ACHIEVE_TYPE_COLLECT_100 = 44
POWER_PVE_DESTROY_A_FORCE = 45
TRIAL_FIGHT_CD = 300
TRIAL_SWEEP_CD = 79200
TRIAL_SWEEP_OPEN_STAGE = 10
UNLOCK_TRAIN_LEVEL = 7
UNLOCK_SMITH_LEVEL = 12
UNLOCK_MIDAS_LEVEL = 13
UNLOCK_BLACKMARKET_LEVEL = 10
UNLOCK_ROOKIE = 5
UNLOCK_CASINO_LEVEL = 15
UNLOCK_ADVANCED_CASINO_LEVEL = 170
UNLOCK_TASK_LEVEL = 10
UNLOCK_ARENA_LEVEL = 35
UNLOCK_CHALLENGE_LEVEL = 20
UNLOCK_GUILD_LEVEL = 40
UNLOCK_TRIAL_LEVEL = 20
UNLOCK_TAVERN_LEVEL = 50
UNLOCK_GTREE_LEVEL = 45
UNLOCK_HERO_BRAVE = 70
UNLOCK_ARENA_3v3_LEVEL = 90
UNLOCK_ARENA_FRIEND_LEVEL = 110
UNLOCK_ARENA_WORLD_LEVEL = 175
UNLOCK_ARENA_STAR_LEVEL = 60
UNLOCK_PET = 130
UNLOCK_ACT_BROKEN = 50
UNLOCK_SOLO_LEVEL = 140
UNLOCK_ONE_KEY_LEVEL = 215
UNLOCK_QLT_SYSTEM = 115
UNLOCK_QLT_PVP = 175
UNLOCK_SMALL_GAME = 65
UNLOCK_JADE_LIMIT = 750
UNLOCK_SUIT_LIMIT = 790
UNLOCK_SKIN_ADVANCE_ITEM = 810
UNLOCK_SUPER_BREAK = 730
UNLOCK_DARE_1 = 20
UNLOCK_DARE_2 = 25
UNLOCK_DARE_3 = 30
UNLOCK_FIGHT_SPEED_LEVEL = 1
UNLOCK_FIGHT_SKIP_LEVEL = 70
UNLOCK_HERO_CRYSTAL = 40
UNLOCK_AIRISLAND_LEVEL = 55
UNLOCK_SEAL_LAND_LEVEL = 160
UNLOCK_TENCASINO_LEVEL = 165
UNLOCK_TRADE_LEVEL = 178
UNLOCK_COLLECT_LEVEL = 185
UNLOCK_ZERO_LEVEL = 0
UNLOCK_GUILD_MILL_LEVEL = 8
UNLOCK_CHAT_WORLD = 25
UNLOCK_FRIEND_EXPLORE = 60
UNLOCK_IH777 = 30
UNLOCK_SANCTUARY = 21
REMARK_LEVEL = 33
UNLOCK_BATTLE_POSITION1 = 5
UNLOCK_BATTLE_POSITION2 = 13
FIRST_PAYMENT_REWARD_NO_PAY = 0
FIRST_PAYMENT_REWARD_UNCLAIMED = 1
FIRST_PAYMENT_REWARD_CLAIMED = 2
HERO_TASK_QUALITY_BLUE = 1
HERO_TASK_QUALITY_YELLOW = 2
HERO_TASK_QUALITY_PURPLE = 3
HERO_TASK_QUALITY_GREEN = 4
HERO_TASK_QUALITY_RED = 5
COINS_CREATE_GUILD = 100000
GEMS_CREATE_GUILD = 40
GUILD_TECH_ID_MIDAS = 5


class GUILD_JOIN_TYPE(IntEnum):
    RECOMMEND = 1
    CREATE = 2
    SEARCH = 3


class SKILL_TIP_TYPE(IntEnum):
    NORMAL = 1
    BRANCH = 2
    NORMAL_BRANCH = 3
    FAITH = 4
    NORMAL_FAITH = 5


ARENA_TYPE_COMMON = 1
ARENA_TYPE_TIMELIMIT_ONE = 2
ARENA_TYPE_SINGLE_3V3 = 3
MAP_ID_ARENA = 7
MAP_ID_DUNGEON = 35
UNLOCK_HERO_TREASURE = 1
EQUIP_POS_ALL = 0
EQUIP_POS_WEAPON = 1
EQUIP_POS_CLOTH = 2
EQUIP_POS_DECORATION = 3
EQUIP_POS_SHOE = 4
EQUIP_POS_JADE = 5
EQUIP_POS_TREASURE = 6
EQUIP_POS_SKIN = 7
EQUIP_POS_BORDER = 8
EQUIP_POS_KERNEL = 9
EQUIP_TYPE_SOUL = 7
EQUIP_TYPE_KERNEL = 8

class PAY_METHOD(IntEnum):
    ALI = 1
    WX = 2


ACT_BOARD_WIDTH = 576
ACT_BOARD_HEIGHT = 447
ACT_BOARD_X = 365
ACT_BOARD_Y = -3
ACT_SCROLL_WIDTH = ACT_BOARD_WIDTH
ACT_SCROLL_HEIGHT = ACT_BOARD_HEIGHT
ACT_SCROLL_X = 0
ACT_SCROLL_Y = 0
ACT_NAV_SCROLL_WIDTH = 334
ACT_NAV_SCROLL_HEIGHT = ACT_BOARD_HEIGHT + 1
ACT_NAV_SCROLL_X = 1
ACT_NAV_SCROLL_Y = -3
ACT_SCROLL_SPACE_1 = 6
ACT_SCROLL_SPACE_2 = 2
ACT_SCROLL_BOARD_WIDTH = ACT_BOARD_WIDTH - 2
ACT_LEFT_OFFSET = 18
ACT_ITEM_STEP = 64
ACT_ITEM_SCALE = 0.7
ACT_ITEM_MASK_SCALE = 0.92
ACT_PROGRESS_WIDTH = 246
AUTO_LV_UP_TIME = 0.5
CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN = 2
CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN = 4
CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN_RECV = 2
CONFIG_PROTOCOL_HEADER_LEN = CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN + CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN
CONFIG_PROTOCOL_HEADER_LEN_RECV = CONFIG_PROTOCOL_HEADER_FIRST_FIELD_LEN + CONFIG_PROTOCOL_HEADER_EXCEPT_FIRST_LEN_RECV
SHADER_SOFT_LIGHT_NORMAL = 7
SHADER_SOFT_LIGHT_DIFFICULT = 15
SHADER_SOFT_LIGHT_DUNGEON = 24
SHADER_SOFT_LIGHT_NIGHTMARE = 24
SHADER_SOFT_LIGHT_DREAM = 24


class LANGUAGE_TYPE(IntEnum):
    ENGLISH = 0
    CHINESE = 1
    FRENCH = 2
    ITALIAN = 3
    GERMAN = 4
    SPANISH = 5
    DUTCH = 6
    RUSSIAN = 7
    KOREAN = 8
    JAPANESE = 9
    HUNGARIAN = 10
    PORTUGUESE = 11
    ARABIC = 12
    CHINESETW = 13
    TURKISH = 14
    THAI = 15
    MALAY = 16
    VIETNAMESE = 17


class TIPS_KIND(StrEnum):
  DEFAULT = "SHOW"
  BAG = "BAG"
  MARKET = "MARKET"
  FORGE = "FORGE"
  JADE_ON = "JADE_ON"
  JADE_OFF = "JADE_OFF"
  JADE_REPLACE = "JADE_REPLACE"
  JADE_COMPARE = "JADE_COMPARE"
  SKIN = "SKIN"
  HERO = "HERO"
  SMITH = "SMITH"
  TREASURE_LEVEL_UP = "TREASURE_LEVEL_UP"
  BORDER_LEVEL_UP = "BORDER_LEVEL_UP"
  EQUIP_HANDLER = "EQUIP_HANDLER"
  ITEM_HANDLER = "ITEM_HANDLER"
  HERO_TEAM = "HERO_TEAM"


class ITEM_TYPE(IntEnum):
    ITEM = 1
    EQUIP = 2


class BUTTON_EFFECT_TYPE(IntEnum):
    NORMAL = 1
    PRESSED = 2
    ENLARGE = 3
    CARD = 4


class RANK_LIST_TYPE(IntEnum):
    HOOK = 1
    FRIEND = 2
    TOWER = 3
    SOLO = 4
    TOWER_DREAM = 5


class BUY_TIPS_TYPE(IntEnum):
    FRIEND = 1
    SEAL_SWEEP = 2
    AIR_ISLAND_SWEEP = 3
    DARE_TIMES = 4
    BATCH_BUY = 5
    BROKEN_TIME = 6
    FIREWORKS = 7
    CANDY_SEND = 8
    BLESSING = 9
    CANDY = 10
    OTHER = 11


class BUY_ITEM_TIPS_TYPE(IntEnum):
    SEAL_CHALLENGE = 1
    SEAL_SWEEP = 2
    CASINO = 3
    ARENA = 4
    TOWER = 5
    BRAVE_ALTAR_ENERGY = 6
    BROKEN = 7
    OTHER = 8
    FIREWORKS = 9
    EDDY_VIT = 10
    EDDY_ITEM = 11
    GUILD_SHOP = 12
    DREAM = 13
    OCEANS = 14


class ITEM_NO_ICON2_ID(IntEnum):
    ITEM_ID_HERO_EXP = ITEM_ID_HERO_EXP
    ITEM_ID_ARENA = ITEM_ID_ARENA
    ITEM_ID_CHIP = ITEM_ID_CHIP
    ITEM_ID_RUNE = ITEM_ID_RUNE_COIN
    ITEM_ID_LUCKY_COIN = ITEM_ID_LUCKY_COIN


class ITEM_RAW_IDS(IntEnum):
    PURPLE_DAFFODIL = 4301
    IBOAT_FOOD = 19402
    SPACE_POWER = 22502
    SEAL_SWEEP = 9201
    SEAL_CHALLENGE = 9401
    BRAVE_ALTAR_ENERGY = 13201
    AIRISLAND_BOAT_EXP = 20801
    MONOPOLY_STAR = 20302
    REVIVE_POINT = 21902
    A_FLAG = 22002
    EDDY_ITEM = 23601
    EDDY_VIT = 23501
    GVM_TICKET = 34401
    GVM_ENERGY = 34501
    CANDY_SCORE = 40302
    CANDY_SCORE_1 = 40301
    DOUBLESEVEN_BAG = 45202
    QLT_PVP_TICKET = 40501
    POWER_PVE_MONSTER_TICKET = 48801
    POWER_PVE_FORT_VIT = 48901
    POWER_PVE_POWER_POINT = 49001
    POWER_PVE_SKILL_POINT = 49101
    POWER_PVE_STONE = 49201
    POWER_PVE_PAPER = 49301
    POWER_PVE_STEEL = 49701
    POWER_PVE_CRYSTAL = 49801
    SMALL_GAME_SCORE = 75401
    SMALL_GAME_COIN = 75101
    TOWER_DEFENSE_EXP = 74902
    TOWER_DEFENSE_GOLD = 75202
    TOWER_DEFENSE_GOLD_BIG = 75201
    TOWER_DEFENSE_HERO_UP_POINT = 75002
    TOWER_DEFENSE_HERO_UP_POINT_BIG = 75001
    TOWER_DEFENSE_TALENT_POINT = 74801
    MERGE_COIN = 78101
    MERGE_VIT = 98701
    MERGE_HEART = 98601
    MERGE_GLOVES = 98401
    MERGE_ICE_BLOCK = 98501
    MERGE_HOURGLASS = 98301
    AUTO_WALK_BLOCK = 113701
    QLT_ENERGY_1 = 98901
    QLT_ENERGY_2 = 98902
    VOID_HOOK_TREASURE_VIT = 99801
    SHIP_GOLD = 25301
    SHIP_GOLD_1 = 25302
    SHIP_VIT = 25401
    SHIP_SCORE = 27301
    SHIP_COLLECT = 26901
    SANCTUARY_MAP_TEAM_VIT = 105701
    SANCTUARY_MAP_VIT = 102001


ITEM_SHIP_GEM = 2007
VOID_GROUP_1 = 1
VOID_GROUP_2 = 2
HERO_WAKE9 = 9
HERO_SATTRS4 = 4
SKILL_TRIGGER_23 = 23


class HERO_FLAG(IntEnum):
    ROOM_OWNER = 32
    ROOMER = 64
    QLT_PVP = 256
    SANCTUARY1_FlAG = 512
    SANCTUARY2_FlAG = 1024
    POWER_CRYSTAL_FlAG = 2048
    OBLATION_FlAG = 4096


class UINT_FLAG(IntEnum):
    TEAM_LEADER = 128


class CORE_FLAG(IntEnum):
    KERNEL_STAR = 15
    KERNEL_BREAK = 240
    KERNEL_STAR_OTHER = 1792


class BTN_TYPE(StrEnum):
  GOLD = "GOLD"
  GREEN = "GREEN"
  RED = "RED"
  WHITE = "WHITE"
  PURPLE = "PURPLE"
  PINK = "PINK"
  GRAY = "GRAY"


class SELECT_HERO_TYPE(StrEnum):
  PVE = "pve"
  VOID_PVE = "void_pve"
  VOID_PVE_HARD = "void_pve_hard"
  VOID_PVE_BOSS = "void_pve_boss"
  VOID_TREASURE = "void_treasure"
  TOWER_TRIAL = "TowerTrial"
  TOWER_DREAM = "TowerDream"
  ARENA_ATK = "ArenaAtk"
  ARENA_DEF = "ArenaDef"
  STAR_ARENA_ATK = "StarArenaAtk"
  STAR_ARENA_DEF = "StarArenaDef"
  FRD_ARENA = "FrdArena"
  GUILD_VICE = "guildVice"
  GUILD_GRAY = "guildGray"
  GUILD_WAR = "guildWar"
  GUILD_WAR_ATK = "guildWar_atk"
  GUILD_WAR_DEF = "guildWar_def"
  CHALLENGE = "challenge"
  AIRISLAND = "airisland"
  FRIEND = "friend"
  GUILD_MILL = "guildmill"
  GUILD_MILL_HARRY = "guildmillharry"
  GUILD_FIGHT = "guildFight"
  FRD_PK = "frdpk"
  BROKEN_BOSS = "brokenboss"
  SWEEP_FOR_BROKEN_BOSS = "sweepforbrokenboss"
  SWEEP_FOR_AIR_ISLAND = "sweepforairisland"
  SWEEP_FOR_COM_ISLAND = "sweepforcomisland"
  SWEEP_FOR_FBOSS = "sweepforfboss"
  SEAL_LAND = "sealland"
  BRAVE_TRIAL = "braveTrial"
  AIRISLAND_BOAT = "airisland_boat"
  DUNGEON_ATK = "dungeon_atk"
  SPACE_TIME_PVE = "space_time_pve"
  SPACE_TIME_SWEEP = "space_time_sweep"
  P3P = "p3p_team"
  ARENA_WORLD = "arena_world"
  SPACE_TIME_EDDY = "space_time_eddy"
  QLT_PVP = "qlt_pvp"
  SPACE_TIME_SHIP = "space_time_ship"
  SPACE_TIME_SHIP_ATK = "space_time_ship_atk"
  SPACE_TIME_SHIP_SEL = "space_time_ship_sel"
  GUILD_STATION_TASK = "guild_station_task"
  GUILD_STATION_BOSS = "guild_station_boss"
  PRESET_TEAM = "preset_team"
  GVM_FIGHT = "gvm_fight"
  POWER_OBSERVE_FIGHT = "power_observe_fight"
  POWER_FORT_FIGHT = "power_fort_fight"
  POWER_MONSTER_FIGHT = "power_monster_fight"
  POWER_RESOURCE_DEFEND = "power_resource_defend"
  SANCTUARY_ARENA_ATK = "sanctuary_arena_atk"
  SANCTUARY_ARENA_DEF = "sanctuary_arena_def"
  SANCTUARY_TEAM = "sanctuary_team"


class HERO_LIST_SORT_TYPE(IntEnum):
    NONE = 0
    LEVEL = 1
    STAR = 2
    STL = 3
    QLT = 4


class HERO_LIST_MODEL_TYPE(IntEnum):
    HEAD = 1
    CARD = 2


class SKIN_LIST_SORT_FESTIVAL_TYPE(IntEnum):
    NONE = 0
    VALENTINE = 1
    MID_AUTUMN = 2
    HALLOWEEN = 3
    SPRING = 4
    THANKSGIVING = 5
    CHRISTMAS = 6
    ANNIVERSARY = 7
    SWIMWEAR = 8
    EASTER = 9
    OTHERS = 10
    CROWN = 11


class SKIN_LIST_SORT_QUALITY_TYPE(IntEnum):
    NONE = 0
    COMMON = 1
    LIMIT = 2
    LEGENDARY = 3
    MYTHIC = 4


SKIN_QUALITY_TYPE = {
    SKIN_LIST_SORT_QUALITY_TYPE.COMMON: [5],
    SKIN_LIST_SORT_QUALITY_TYPE.LIMIT: [1, 3, 6],
    SKIN_LIST_SORT_QUALITY_TYPE.LEGENDARY: [2, 4, 7],
    SKIN_LIST_SORT_QUALITY_TYPE.MYTHIC: [8, 9, 10]
}


MAX_BATCH_BUY_NUM = 999999
MAX_SUMMON_TIMES = 500


class UI_PAGE(StrEnum):
  NONE = "none"
  HOOK = "hook"
  ARENA = "arena"
  ARENA_NORMAL = "arena_normal"
  GUILD = "guild"
  FRIEND = "friend"
  ACHIEVE = "achieve"
  HEROTASK = "herotask"
  TASK = "task"
  MIDAS = "midas"
  TRIAL = "trial"
  CASINO = "casino"
  CASINO_LOW = "casino_low"
  CASINO_HIGH = "casino_high"
  SUMMON = "summon"
  SUMMON_HIGH = "summon_high"
  SUMMON_LOVE = "summon_love"
  BRAVE = "brave"
  BLACKMARKET = "blackmarket"
  MONTHLY_MARKET = "monthly_market"
  DEVOUR_MARKET = "devour_market"
  SEALLAND_MARKET = "sealland_market"
  GUILD_MARKET = "guild_market"
  CASINO_MARKET = "casino_market"
  ARENA_MARKET = "arena_market"
  SUMMONSPE = "summonspe"
  HEROLIST = "herolist"
  HEROMARKET = "heromarket"
  SMITH = "smith"
  DEVOUR = "devour"
  HEROFORGE = "heroforge"
  BRAVE_SHOP = "braveshop"
  DARE = "dare_coin"
  DARE_2 = "dare_chall"
  DARE_3 = "dare_hero"
  PVP3_SHOP = "pvp3_shop"
  BROKEN_BOSS = "broken_boss"
  DUNGEON = "dungeon"
  SIGN_IN = "sign_in"
  SEAL_LAND = "seal_land"
  PET = "pet"
  ISLAND = "island"
  SPACE_TIME = "space_time"
  BAG = "bag"
  DWARF = "dwarf"
  SKIN = "skin"
  QLT_HALL = "qlt_hall"
  BRAVE_SHOP2 = "brave_shop"
  COLEECT = "collect"
  DREAM_TOWER = "dream_tower"


class UI_UNLOCK_LEVEL(IntEnum):
    ARENA = UNLOCK_ARENA_LEVEL
    ARENA_NORMAL = UNLOCK_ARENA_LEVEL
    GUILD = UNLOCK_GUILD_LEVEL
    HEROTASK = UNLOCK_TAVERN_LEVEL
    TASK = UNLOCK_TASK_LEVEL
    TRIAL = UNLOCK_TRIAL_LEVEL
    CASINO = UNLOCK_CASINO_LEVEL
    BRAVE = UNLOCK_HERO_BRAVE
    SUMMONSPE = UNLOCK_GTREE_LEVEL
    DARE = UNLOCK_DARE_1
    DARE_2 = UNLOCK_DARE_2
    DARE_3 = UNLOCK_DARE_3
    SEAL_LAND = UNLOCK_SEAL_LAND_LEVEL
    DUNGEON = UNLOCK_SOLO_LEVEL
    CASINO_LOW = UNLOCK_CASINO_LEVEL
    PET = UNLOCK_PET
    QLT_HALL = UNLOCK_QLT_SYSTEM
    ISLAND = UNLOCK_AIRISLAND_LEVEL
    COLEECT = UNLOCK_COLLECT_LEVEL


class NEWBIE_CHAPTER(IntEnum):
  HOOK_STAGE = 1
  HERO_LV_NUM = 2
  GET_HERO = 3
  WEAR_EQUIP = 4
  WEAR_TREASURE = 5
  WEAR_JADE = 6
  ACTIVATE_PET = 7
  PET_LV = 8
  PET_ADVANCE = 9
  PET_AUREOLE = 10
  DECOMPOSE_HERO = 11
  BLACK_MARKET_BUY = 12
  COMPOSE_EQUIP = 13
  TAVERN_TASK = 14
  TRIAL_STAGE = 15
  JOIN_GUILD = 16
  GUILD_SKILL_UP = 17
  STATION_TASK = 18
  STATION_LV = 19
  GUILD_BOSS_FIGHT = 20
  GUILD_MARKET_BUY = 21
  ISLAND_ADVENTURE = 22
  ISLAND_SHIP_UP = 23
  ISLAND_EXPLORE = 24
  BRAVE_STAGE = 25
  BRAVE_ALTAR = 26
  BRAVE_CHEST = 27
  DUNGEON_STAGE = 28
  DUNGEON_MARKET_BUY = 29
  SEALAND_STAGE = 30
  SEALAND_MARKET_BUY = 31
  ARENA_WIN = 32
  P3P_ARENA_WIN = 33
  WORLD_ARENA_WIN = 34
  WORLD_ARENA_TASK = 35
  ARENA_MARKET_BUY = 36
  FRIEND_NUM = 37
  SEND_HEART = 38
  ACTIVITY_BOSS_STAGE = 39
  HIGH_SUMMON = 40
  FRIEND_SUMMON = 41
  SEER_SUMMON = 42
  SEER_REPLACE = 43
  NORMAL_CASINO = 44
  HIGH_CASINO = 45
  HOOK_GOLD = 46
  HOOK_SOUL = 47
  PLAYER_LV = 48
  BATTLE_HERO_NUM = 49
  FRAGMENT_COMPOSE = 50
  FORGE_COMPOSE = 63
  STAR_TREE_LV = 59
  ST_SHIP_EXPLORE = 76
  ST_SUMMON = 77
  ST_EDDY_FIGHT = 78
  ST_EDDY_NUM = 79
  ST_MAP_PLAY = 80
  ST_MAP_AREA = 81
  ST_MAP_FLOOR = 82
  COLLECTION_SUMMON = 83
  DREAM_STAGE = 84
  STAR_PET_NUM = 85
  PET_BUFF = 86


class NEWBIE_CHALLENGE(IntEnum):
  GET_HERO = 3
  COMPOSE_SPACE_HERO = 51
  ACTIVATE_SPACE_SKILL = 52
  GET_EQUIP = 53
  GET_SUIT_EQUIP = 61
  GET_JOB_EQUIP = 55
  GET_ADVANCE_EQUIP = 56
  GET_JADE = 57
  PET_NUM = 58
  STAR_TREE_LV = 59
  STAR_PET_NUM = 60
  PET_MAX_LV = 62
  HERO_TREE_CORE = 73
  HERO_QLT = 68
  HOME_ISLAND_NUM = 69
  HOME_ISLAND_COMFORT = 70
  GET_SKIN = 71
  HERO_TREE_UP = 72
  GET_ADV_STAR_EQUIP = 74
  COLLECT_STAR = 75


class NEWBIE_CONDITION(IntEnum):
  HERO_GROUP = 1002
  HERO_STAR = 1003
  TASK_LV = 1004
  BOSS_HURT = 1005
  BRAVE_STAGE = 1006
  BRAVE_BOX = 1007
  TEAM_NUM = 1010
  HOOK_STAGE = 500
  EQUIP_NUM = 501
  EQUIP_QLT = 502
  EQUIP_POS = 503
  GUILD_SKILL = 507
  STATION_LV = 508
  ISLAND_SHIP = 509
  DUNGEON_STAGE = 510
  HERO_LV = 514
  PET_ID = 516
  PET_LV = 517
  PET_STAR = 518
  PET_AUREOLE = 519
  PET_AUREOLE_NUM = 520
  PET_RUNE = 521
  PET_RUNE_NUM = 522
  PET_AUREOLE_LV = 528
  BROKEN_STAGE = 530
  EQUIP_STAR = 531
  DREAM_STAGE = 538
  SATTR_SKILL = 1011
  EQUIP_CON_QLT = 1012
  EQUIP_CON_LV = 1014
  EQUIP_CON_POS = 1015
  EQUIP_CON_EQ_QLT = 1017
  EQUIP_CON_EQ_LV = 1018
  EQUIP_CON_TYPE = 1019
  COMPLETE_TASK = 523
  STOWER_LV = 524
  SPET_LV = 525
  SPET_GROUP = 526
  SPET_JOB = 527
  SPET_NUM = 539
  HERO_TREE_ADVANCE = 1020
  HERO_TREE_LV = 1021
  HERO_TREE_SKILL = 1022
  HERO_CORE_STAR = 1023
  SKIN_TYPE = 1024
  HERO_QLT = 1025
  RESONANCE_STAR = 1026
  ISLAND_NUM = 533
  ISLAND_COMFORT = 534
  COLEECTION_STAR = 535
  COLEECTION_NUM = 536


CUSTOM_SUMMON_ID = 81078


class POWER_PVE(IntEnum):
    LOOK_MAX = 3


LONG_PRESS_TAG = 654321
SUPER_BREAK_START_LV = 400
NEW_YEAR_DEVIL_MAX_COMPLETE_TIMES = 4
